public class pppp {

    public static void aa(){
        
        list<Account> acc = new list<Account>();
        
        acc.add(new account(name = 'Ashokaaaa11t54e54ey'));
        acc.add(new account(name = 'Dikshaaaa111g154yd5'));
        insert acc;


list<Opportunity> opp = new list<Opportunity>();
        
        opp.add(new Opportunity(name =' 1 Opportunitdfghy1' , accountid = acc[0].Id, StageName = 'Closed Won', closedate =  Date.newInstance(2021, 01, 01)));
        opp.add(new Opportunity(name =' 2 Opportunfgity1' , accountid = acc[0].Id, StageName = 'Closed Won', closedate =  Date.newInstance(2021, 01, 01)));
        opp.add(new Opportunity(name =' 3 Opportunidfgty1' , accountid = acc[0].Id, StageName = 'Prospecting', closedate =  Date.newInstance(2021, 01, 01)));
        opp.add(new Opportunity(name =' 4 Opportunidfgty1' , accountid = acc[1].Id, StageName = 'Closed Won', closedate =  Date.newInstance(2021, 01, 01)));
        opp.add(new Opportunity(name =' 5 Opportundfgity1' , accountid = acc[1].Id, StageName = 'Prospecting', closedate =  Date.newInstance(2021, 01, 01)));
        opp.add(new Opportunity(name =' 6 Opportdfgunity1' , accountid = acc[1].Id, StageName = 'Prospecting', closedate =  Date.newInstance(2021, 01, 01)));
        insert opp;
        
                
    }
    
}